apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: security-extras
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Waddenn/projet-etude-M1.git
    targetRevision: main
    path: kubernetes/extras/security
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
