apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ticketdb
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4

  bootstrap:
    initdb:
      database: app
      owner: app

  storage:
    size: 1Gi

  resources:
    requests: { cpu: 50m, memory: 128Mi }
    limits:   { memory: 256Mi }

  monitoring:
    enablePodMonitor: true

  postgresql:
    parameters:
      max_connections: "50"
      shared_buffers: "64MB"
