apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- database.yaml
- deployment.yaml
- service.yaml
- hpa.yaml
- ingress.yaml
- servicemonitor.yaml
- prometheusrule.yaml
- networkpolicy.yaml
- dashboard.yaml
images:
- name: ghcr.io/waddenn/projet-etude-app-demo
  digest: sha256:bbfeff71728035f0be18e03df111a885273f1cb51408eb13bc4e0df8d67a1692
