apiVersion: v1
kind: Service
metadata:
  name: infisical-ext
  namespace: security
  labels:
    app.kubernetes.io/component: infisical
    app.kubernetes.io/name: infisical
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: infisical
    app.kubernetes.io/name: infisical
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 30808
