apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-ext
  namespace: security
  labels:
    app.kubernetes.io/component: vaultwarden
    app.kubernetes.io/name: vaultwarden
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: vaultwarden
    app.kubernetes.io/instance: vaultwarden
    app.kubernetes.io/name: vaultwarden
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 30808
